{% set name = "google-cloud-trace" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_trace-{{ version }}.tar.gz
  sha256: 68703bfc93718083f061d9130a3852e3181ec1b6b796b76856997c28f51b9595

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.trace
    - google.cloud.trace_v1
    - google.cloud.trace_v2
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-trace
  summary: Google Cloud Trace API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "The Stackdriver Trace API sends application trace data to Stackdriver Trace for viewing. Trace data is collected for all App Engine applications by default. Trace data from other applications can be provided using this API.\nSee the [quick start guide](https://googleapis.dev/python/cloudtrace/latest/index.html#quick-start)."

  doc_url: https://cloud.google.com/python/docs/reference/cloudtrace/latest
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-trace

extra:
  recipe-maintainers:
    - xylar
    - parthea
