{% set name = "google-cloud-trace" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e1b16842067cc28f5b36cf68f11e32f38bb87e3d2450484da5cf9be051879fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.trace
    - google.cloud.trace_v1
    - google.cloud.trace_v2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-trace
  summary: Google Cloud Trace API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "The Stackdriver Trace API sends application trace data to Stackdriver Trace for viewing. Trace data is collected for all App Engine applications by default. Trace data from other applications can be provided using this API.\nSee the [quick start guide](https://googleapis.dev/python/cloudtrace/latest/index.html#quick-start)."

  doc_url: https://cloud.google.com/python/docs/reference/cloudtrace/latest
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-trace

extra:
  recipe-maintainers:
    - xylar
    - parthea
